// 📋 DATA — you don't need to edit this file

export const spells = [
  { id: 1, name: "Fireball", element: "fire", power: 85, description: "Hurls a blazing sphere that explodes on impact" },
  { id: 2, name: "Inferno Wave", element: "fire", power: 92, description: "Sends a sweeping wall of flames across the battlefield" },
  { id: 3, name: "Ember Shield", element: "fire", power: 45, description: "Creates a protective barrier of smoldering embers" },
  { id: 4, name: "Magma Burst", element: "fire", power: 78, description: "Erupts molten rock from beneath the ground" },
  { id: 5, name: "Phoenix Flare", element: "fire", power: 95, description: "Channels the rebirth flame of the phoenix" },
  { id: 6, name: "Frost Nova", element: "ice", power: 72, description: "Radiates a freezing blast in all directions" },
  { id: 7, name: "Glacial Spike", element: "ice", power: 68, description: "Launches a razor-sharp shard of enchanted ice" },
  { id: 8, name: "Blizzard Veil", element: "ice", power: 80, description: "Summons a localized blizzard that obscures and slows" },
  { id: 9, name: "Frozen Tomb", element: "ice", power: 88, description: "Encases the target in an unbreakable ice prison" },
  { id: 10, name: "Snowdrift Step", element: "ice", power: 35, description: "Glide across any surface on a trail of frost" },
  { id: 11, name: "Thunder Strike", element: "lightning", power: 90, description: "Calls a bolt of lightning from the sky" },
  { id: 12, name: "Chain Lightning", element: "lightning", power: 82, description: "Arcs between multiple targets with electric fury" },
  { id: 13, name: "Spark Shield", element: "lightning", power: 50, description: "Surrounds the caster in a crackling electric field" },
  { id: 14, name: "Storm Pulse", element: "lightning", power: 75, description: "Releases a shockwave of compressed static energy" },
  { id: 15, name: "Voltaic Rush", element: "lightning", power: 65, description: "Dash forward wreathed in electric current" },
  { id: 16, name: "Stone Wall", element: "earth", power: 55, description: "Raises a solid wall of stone from the ground" },
  { id: 17, name: "Earthquake", element: "earth", power: 94, description: "Shakes the ground violently in a wide radius" },
  { id: 18, name: "Vine Grasp", element: "earth", power: 42, description: "Animated vines erupt to entangle targets" },
  { id: 19, name: "Boulder Toss", element: "earth", power: 70, description: "Rips a massive boulder from the earth and hurls it" },
  { id: 20, name: "Mud Slide", element: "earth", power: 48, description: "Creates a slippery torrent of mud and debris" },
  { id: 21, name: "Arcane Missile", element: "arcane", power: 60, description: "Fires homing bolts of pure magical energy" },
  { id: 22, name: "Mana Surge", element: "arcane", power: 88, description: "Channels raw mana into a devastating beam" },
  { id: 23, name: "Dispel Ward", element: "arcane", power: 40, description: "Unravels enemy enchantments and protections" },
  { id: 24, name: "Chrono Shift", element: "arcane", power: 96, description: "Briefly warps the flow of time around the caster" },
  { id: 25, name: "Rune Trap", element: "arcane", power: 55, description: "Inscribes an invisible rune that detonates on contact" },
  { id: 26, name: "Shadow Bolt", element: "shadow", power: 73, description: "Launches a projectile of condensed darkness" },
  { id: 27, name: "Void Step", element: "shadow", power: 58, description: "Teleport a short distance through the shadow realm" },
  { id: 28, name: "Nightmare Hex", element: "shadow", power: 82, description: "Afflicts the target with paralyzing visions of dread" },
  { id: 29, name: "Soul Drain", element: "shadow", power: 77, description: "Siphons life force from the target to the caster" },
  { id: 30, name: "Eclipse Shroud", element: "shadow", power: 64, description: "Cloaks an area in impenetrable magical darkness" },
  { id: 31, name: "Flame Whip", element: "fire", power: 62, description: "Conjures a lash of living fire with deadly reach" },
  { id: 32, name: "Icicle Barrage", element: "ice", power: 74, description: "Fires a rapid volley of razor-thin ice needles" },
  { id: 33, name: "Gravity Well", element: "arcane", power: 85, description: "Creates a crushing sphere of intensified gravity" },
  { id: 34, name: "Thorn Burst", element: "earth", power: 52, description: "Spikes of hardened wood erupt from nearby surfaces" },
  { id: 35, name: "Dark Pact", element: "shadow", power: 91, description: "Sacrifices health to unleash overwhelming shadow magic" },
];

export const elements = ["all", "fire", "ice", "lightning", "earth", "arcane", "shadow"];
